using SharedAbstractions.Enums.Attributes;

namespace SharedAbstractions.Enums
{
    public enum CountriesEnum
    {
        [CountryInfo("01", "Afganistán")] Afganistán,
        [CountryInfo("02", "Albania")] Albania,
        [CountryInfo("03", "Alemania")] Alemania,
        [CountryInfo("04", "Andorra")] Andorra,
        [CountryInfo("05", "Angola")] Angola,
        [CountryInfo("06", "Antigua y Barbuda")] Antigua_y_Barbuda,
        [CountryInfo("07", "Arabia Saudita")] Arabia_Saudita,
        [CountryInfo("08", "Argelia")] Argelia,
        [CountryInfo("09", "Argentina")] Argentina,
        [CountryInfo("10", "Armenia")] Armenia,
        [CountryInfo("11", "Australia")] Australia,
        [CountryInfo("12", "Austria")] Austria,
        [CountryInfo("13", "Azerbaiyán")] Azerbaiyán,
        [CountryInfo("14", "Bahamas")] Bahamas,
        [CountryInfo("15", "Bangladés")] Bangladés,
        [CountryInfo("16", "Barbados")] Barbados,
        [CountryInfo("17", "Baréin")] Baréin,
        [CountryInfo("18", "Bélgica")] Bélgica,
        [CountryInfo("19", "Belice")] Belice,
        [CountryInfo("20", "Benín")] Benín,
        [CountryInfo("21", "Bielorrusia")] Bielorrusia,
        [CountryInfo("22", "Birmania / Myanmar")] Birmania__Myanmar,
        [CountryInfo("23", "Bolivia")] Bolivia,
        [CountryInfo("24", "Bosnia y Herzegovina")] Bosnia_y_Herzegovina,
        [CountryInfo("25", "Botsuana")] Botsuana,
        [CountryInfo("26", "Brasil")] Brasil,
        [CountryInfo("27", "Brunéi")] Brunéi,
        [CountryInfo("28", "Bulgaria")] Bulgaria,
        [CountryInfo("29", "Burkina Faso")] Burkina_Faso,
        [CountryInfo("30", "Burundi")] Burundi,
        [CountryInfo("31", "Bután")] Bután,
        [CountryInfo("32", "Cabo Verde")] Cabo_Verde,
        [CountryInfo("33", "Camboya")] Camboya,
        [CountryInfo("34", "Camerún")] Camerún,
        [CountryInfo("35", "Canadá")] Canadá,
        [CountryInfo("36", "Catar")] Catar,
        [CountryInfo("37", "Chad")] Chad,
        [CountryInfo("38", "Chile")] Chile,
        [CountryInfo("39", "China")] China,
        [CountryInfo("40", "Chipre")] Chipre,
        [CountryInfo("41", "Colombia")] Colombia,
        [CountryInfo("42", "Comoras")] Comoras,
        [CountryInfo("43", "Congo")] Congo,
        [CountryInfo("44", "Corea del Norte")] Corea_del_Norte,
        [CountryInfo("45", "Corea del Sur")] Corea_del_Sur,
        [CountryInfo("46", "Costa de Marfil")] Costa_de_Marfil,
        [CountryInfo("47", "Costa Rica")] Costa_Rica,
        [CountryInfo("48", "Croacia")] Croacia,
        [CountryInfo("49", "Cuba")] Cuba,
        [CountryInfo("50", "Dinamarca")] Dinamarca,
        [CountryInfo("51", "Dominica")] Dominica,
        [CountryInfo("52", "Ecuador")] Ecuador,
        [CountryInfo("53", "Egipto")] Egipto,
        [CountryInfo("54", "El Salvador")] El_Salvador,
        [CountryInfo("55", "Emiratos Árabes Unidos")] Emiratos_Árabes_Unidos,
        [CountryInfo("56", "Eritrea")] Eritrea,
        [CountryInfo("57", "Eslovaquia")] Eslovaquia,
        [CountryInfo("58", "Eslovenia")] Eslovenia,
        [CountryInfo("59", "España")] España,
        [CountryInfo("60", "Estados Unidos")] Estados_Unidos,
        [CountryInfo("61", "Estonia")] Estonia,
        [CountryInfo("62", "Esuatini / Suazilandia")] Esuatini__Suazilandia,
        [CountryInfo("63", "Etiopía")] Etiopía,
        [CountryInfo("64", "Filipinas")] Filipinas,
        [CountryInfo("65", "Finlandia")] Finlandia,
        [CountryInfo("66", "Fiyi")] Fiyi,
        [CountryInfo("67", "Francia")] Francia,
        [CountryInfo("68", "Gabón")] Gabón,
        [CountryInfo("69", "Gambia")] Gambia,
        [CountryInfo("70", "Georgia")] Georgia,
        [CountryInfo("71", "Ghana")] Ghana,
        [CountryInfo("72", "Granada")] Granada,
        [CountryInfo("73", "Grecia")] Grecia,
        [CountryInfo("74", "Guatemala")] Guatemala,
        [CountryInfo("75", "Guinea")] Guinea,
        [CountryInfo("76", "Guinea Ecuatorial")] Guinea_Ecuatorial,
        [CountryInfo("77", "Guinea-Bisáu")] Guinea_Bisáu,
        [CountryInfo("78", "Guyana")] Guyana,
        [CountryInfo("79", "Haití")] Haití,
        [CountryInfo("80", "Honduras")] Honduras,
        [CountryInfo("81", "Hungría")] Hungría,
        [CountryInfo("82", "India")] India,
        [CountryInfo("83", "Indonesia")] Indonesia,
        [CountryInfo("84", "Irak")] Irak,
        [CountryInfo("85", "Irán")] Irán,
        [CountryInfo("86", "Irlanda")] Irlanda,
        [CountryInfo("87", "Islandia")] Islandia,
        [CountryInfo("88", "Islas Marshall")] Islas_Marshall,
        [CountryInfo("89", "Islas Salomón")] Islas_Salomón,
        [CountryInfo("90", "Israel")] Israel,
        [CountryInfo("91", "Italia")] Italia,
        [CountryInfo("92", "Jamaica")] Jamaica,
        [CountryInfo("93", "Japón")] Japón,
        [CountryInfo("94", "Jordania")] Jordania,
        [CountryInfo("95", "Kazajistán")] Kazajistán,
        [CountryInfo("96", "Kenia")] Kenia,
        [CountryInfo("97", "Kirguistán")] Kirguistán,
        [CountryInfo("98", "Kiribati")] Kiribati,
        [CountryInfo("99", "Kuwait")] Kuwait,
        [CountryInfo("100", "Laos")] Laos,
        [CountryInfo("101", "Lesoto")] Lesoto,
        [CountryInfo("102", "Letonia")] Letonia,
        [CountryInfo("103", "Líbano")] Líbano,
        [CountryInfo("104", "Liberia")] Liberia,
        [CountryInfo("105", "Libia")] Libia,
        [CountryInfo("106", "Liechtenstein")] Liechtenstein,
        [CountryInfo("107", "Lituania")] Lituania,
        [CountryInfo("108", "Luxemburgo")] Luxemburgo,
        [CountryInfo("109", "Macedonia del Norte")] Macedonia_del_Norte,
        [CountryInfo("110", "Madagascar")] Madagascar,
        [CountryInfo("111", "Malasia")] Malasia,
        [CountryInfo("112", "Malaui")] Malaui,
        [CountryInfo("113", "Maldivas")] Maldivas,
        [CountryInfo("114", "Mali")] Mali,
        [CountryInfo("115", "Malta")] Malta,
        [CountryInfo("116", "Marruecos")] Marruecos,
        [CountryInfo("117", "Mauricio")] Mauricio,
        [CountryInfo("118", "Mauritania")] Mauritania,
        [CountryInfo("119", "México")] México,
        [CountryInfo("120", "Micronesia")] Micronesia,
        [CountryInfo("121", "Moldavia")] Moldavia,
        [CountryInfo("122", "Mónaco")] Mónaco,
        [CountryInfo("123", "Mongolia")] Mongolia,
        [CountryInfo("124", "Montenegro")] Montenegro,
        [CountryInfo("125", "Mozambique")] Mozambique,
        [CountryInfo("126", "Namibia")] Namibia,
        [CountryInfo("127", "Nauru")] Nauru,
        [CountryInfo("128", "Nepal")] Nepal,
        [CountryInfo("129", "Nicaragua")] Nicaragua,
        [CountryInfo("130", "Níger")] Níger,
        [CountryInfo("131", "Nigeria")] Nigeria,
        [CountryInfo("132", "Noruega")] Noruega,
        [CountryInfo("133", "Nueva Zelanda")] Nueva_Zelanda,
        [CountryInfo("134", "Omán")] Omán,
        [CountryInfo("135", "Países Bajos")] Países_Bajos,
        [CountryInfo("136", "Pakistán")] Pakistán,
        [CountryInfo("137", "Palaos")] Palaos,   
        [CountryInfo("150", "Palestina")] Palestina,
        [CountryInfo("151", "Panamá")] Panamá,
        [CountryInfo("152", "Papúa Nueva Guinea")] Papúa_Nueva_Guinea,
        [CountryInfo("153", "Paraguay")] Paraguay,
        [CountryInfo("154", "Perú")] Perú,
        [CountryInfo("155", "Polonia")] Polonia,
        [CountryInfo("156", "Portugal")] Portugal,
        [CountryInfo("157", "Reino Unido")] Reino_Unido,
        [CountryInfo("158", "República Centroafricana")] República_Centroafricana,
        [CountryInfo("159", "República Checa")] República_Checa,
        [CountryInfo("160", "República Democrática del Congo")] República_Democrática_del_Congo,
        [CountryInfo("161", "República Dominicana")] República_Dominicana,
        [CountryInfo("162", "Ruanda")] Ruanda,
        [CountryInfo("163", "Rumania")] Rumania,
        [CountryInfo("164", "Rusia")] Rusia,
        [CountryInfo("165", "Samoa")] Samoa,
        [CountryInfo("166", "San Cristóbal y Nieves")] San_Cristóbal_y_Nieves,
        [CountryInfo("167", "San Marino")] San_Marino,
        [CountryInfo("168", "San Vicente y las Granadinas")] San_Vicente_y_las_Granadinas,
        [CountryInfo("169", "Santa Lucía")] Santa_Lucía,
        [CountryInfo("170", "Santa Sede / Ciudad del Vaticano")] Santa_Sede__Ciudad_del_Vaticano,
        [CountryInfo("171", "Santo Tomé y Príncipe")] Santo_Tomé_y_Príncipe,
        [CountryInfo("172", "Senegal")] Senegal,
        [CountryInfo("173", "Serbia")] Serbia,
        [CountryInfo("174", "Seychelles")] Seychelles,
        [CountryInfo("175", "Sierra Leona")] Sierra_Leona,
        [CountryInfo("176", "Singapur")] Singapur,
        [CountryInfo("177", "Siria")] Siria,
        [CountryInfo("178", "Somalia")] Somalia,
        [CountryInfo("179", "Sri Lanka")] Sri_Lanka,
        [CountryInfo("180", "Sudáfrica")] Sudáfrica,
        [CountryInfo("181", "Sudán")] Sudán,
        [CountryInfo("182", "Sudán del Sur")] Sudán_del_Sur,
        [CountryInfo("183", "Suecia")] Suecia,
        [CountryInfo("184", "Suiza")] Suiza,
        [CountryInfo("185", "Surinam")] Surinam,
        [CountryInfo("186", "Tailandia")] Tailandia,
        [CountryInfo("187", "Tanzania")] Tanzania,
        [CountryInfo("188", "Tayikistán")] Tayikistán,
        [CountryInfo("189", "Timor Oriental")] Timor_Oriental,
        [CountryInfo("190", "Togo")] Togo,
        [CountryInfo("191", "Tonga")] Tonga,
        [CountryInfo("192", "Trinidad y Tobago")] Trinidad_y_Tobago,
        [CountryInfo("193", "Túnez")] Túnez,
        [CountryInfo("194", "Turkmenistán")] Turkmenistán,
        [CountryInfo("195", "Turquía")] Turquía,
        [CountryInfo("196", "Tuvalu")] Tuvalu,
        [CountryInfo("197", "Ucrania")] Ucrania,
        [CountryInfo("198", "Uganda")] Uganda,
        [CountryInfo("199", "Uruguay")] Uruguay,
        [CountryInfo("200", "Uzbekistán")] Uzbekistán,
        [CountryInfo("201", "Vanuatu")] Vanuatu,
        [CountryInfo("202", "Venezuela")] Venezuela,
        [CountryInfo("203", "Vietnam")] Vietnam,
        [CountryInfo("204", "Yemen")] Yemen,
        [CountryInfo("205", "Yibuti")] Yibuti,
        [CountryInfo("206", "Zambia")] Zambia,
        [CountryInfo("207", "Zimbabue")] Zimbabue
    }
}